<div class="themes-demo-wrap">
	<div class="theme-demo-option">
		<h2 class="themes-demo-title"><?php echo $this->__('Theme Color') ?></h2>
		<div class="cl-table">
			<div class="cl-tr">
				<div class="cl-td cl-td-layout1"><a href="<?php echo $this->getUrl().'?___store=en' ?>" title="gray"><span></span><?php echo $this->__('Gray') ?></a></div>
							
				<div class="cl-td cl-td-layout2"><a href="<?php echo $this->getUrl().'?___store=ge' ?>" title="blue"><span></span><?php echo $this->__('Blue') ?></a></div>
				<div class="cl-td cl-td-layout3"><a href="<?php echo $this->getUrl().'?___store=fr' ?>" title="red"><span></span><?php echo $this->__('Red') ?></a></div>
				
			</div>
			
		</div>
		<div class="control inactive"><a href="javascript:void(0)"><i class="fa fa-cog fa-spin"></i></a></div>
	</div>
	
</div>
<script type="text/javascript">
	jQuery(document).ready( function($){
		$('.control').click(function(){
			if($(this).hasClass('inactive')) {
				$(this).removeClass('inactive');
				$(this).addClass('active');
				$('.themes-demo-wrap').animate({left:'0'}, 500);
			} else {
				$(this).addClass('inactive');
				$('.themes-demo-wrap').animate({left:'-260px'}, 500);
			}
		});
	});
</script>