<?php
$store = Mage::app()->getStore();
$code = $store->getCode();
?>
<?php $_helper = Mage::helper('catalog/category') ?>
<?php $_categories = $_helper->getStoreCategories() ?>
<!-- slider area -->
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('homepage-slider')->toHtml(); ?>
<?php echo $this->getLayout()->createBlock('filterproducts/new_home_list')->setTemplate('filterproducts/new.phtml')->toHtml(); ?>
<!-- Categories items container -->
<?php if (count($_categories) > 0): ?>
    <div class="container">
        <div class="total-item-cont clearfix">
            <div id="carousel2" class="owl-carousel owl-theme" style="display: block">
            <?php $i = 0; ?>
            <?php foreach ($_categories as $_category): ?>
                <?php if ($i++ == 6) break; ?>
                <?php $ID = $_category->getId(); ?>
                <div class="item">
                <div class="total-item-box">
                    <div class="img-holder">
                        <?php $thumb = Mage::getModel('catalog/category')->load($ID)->getThumbnail(); ?>
                        <a href="<?php echo $_helper->getCategoryUrl($_category); ?>">
                            <img src="<?php echo Mage::getBaseUrl('media') . 'catalog/category/' . $thumb; ?>">
                        </a>
                    </div>
                    <div class="item-desc text-center">
                        <?php $products_count = Mage::getModel('catalog/category')->load($_category->getId())
                            ->getProductCount(); ?>
                        <span class="total-number"><?php  echo ($products_count); ?></span>
                        <span class="item-txt">items</span>
                        <a id="<?php echo $ID ?>" class="item-title" href="<?php echo $_helper->getCategoryUrl($_category); ?>">
                            <?php echo $_category->getName() ?>
                        </a>
                    </div>
                </div>
                </div>
            <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php echo $this->getLayout()->createBlock('filterproducts/new_home_list')->setTemplate('filterproducts/best-sellers.phtml')->toHtml(); ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('homepage-tab-content')->toHtml(); ?>