<?php 
$store = Mage::app()->getStore();
$code  = $store->getCode();
?>

<!-- slider area -->
<div class="slider-area">
    <div class="main-banner">
        <div id="slider" class="owl-carousel owl-theme">
            <div class="item"><img src="<?php echo $this->getSkinUrl('images/studytable_bannerq.jpg') ?>" alt=""></div>
            <div class="item"><img src="<?php echo $this->getSkinUrl('images/wilmax_banner_2_1.jpg') ?>" alt=""></div>
        </div>
    </div>
    <div class="side-ad-area">
        <img src="<?php echo $this->getSkinUrl('images/top-ad.jpg') ?>" alt="">
    </div>
</div>

<!-- top info container -->
<div class="top-info-cont clearfix">
    <div class="world-map">
        <div class="world-map-detail">
            <p>Lorem ipsum dolor sitccums anamet</p>
        </div>
    </div>
    <div class="top-info-detail">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam scelerisque </p>
        <a href="">read more</a>
    </div>
</div>

<?php echo $this->getLayout()->createBlock('filterproducts/new_home_list')->setProductCount(16)->setTemplate('filterproducts/new.phtml')->toHtml();?>

<!-- total items container -->
<div  class="container">
    <div class="total-item-cont clearfix">

        <div class="total-item-box">
            <div class="img-holder">
                <a href=""><img src="<?php echo $this->getSkinUrl('images/item-img-01.jpg') ?>" alt=""></a>
            </div>
            <div class="item-desc text-center">
                <span class="total-number">56</span>
                <span class="item-txt">items</span>
                <a href="" class="item-title">furniture</a>
            </div>
        </div>
        <div class="total-item-box">
            <div class="img-holder">
                <a href=""><img  src="<?php echo $this->getSkinUrl('images/item-img-02.jpg') ?>" alt=""></a>
            </div>
            <div class="item-desc text-center">
                <span class="total-number">46</span>
                <span class="item-txt">items</span>
                <a href="" class="item-title">furnishing</a>
            </div>
        </div>
        <div class="total-item-box">
            <div class="img-holder">
                <a href=""><img  src="<?php echo $this->getSkinUrl('images/item-img-03.jpg') ?>" alt=""></a>
            </div>
            <div class="item-desc text-center">
                <span class="total-number">67</span>
                <span class="item-txt">items</span>
                <a href="" class="item-title">light</a>
            </div>
        </div>
        <div class="total-item-box">
            <div class="img-holder">
                <a href=""><img  src="<?php echo $this->getSkinUrl('images/item-img-04.jpg') ?>" alt=""></a>
            </div>
            <div class="item-desc text-center">
                <span class="total-number">32</span>
                <span class="item-txt">items</span>
                <a href="" class="item-title">carpets</a>
            </div>
        </div>
        <div class="total-item-box">
            <div class="img-holder">
                <a href=""><img src="<?php echo $this->getSkinUrl('images/item-img-05.jpg') ?>" alt=""></a>
            </div>
            <div class="item-desc text-center">
                <span class="total-number">12</span>
                <span class="item-txt">items</span>
                <a href="" class="item-title">home accessories</a>
            </div>
        </div>
        <div class="total-item-box">
            <div class="img-holder">
                <a href=""><img  src="<?php echo $this->getSkinUrl('images/item-img-06.jpg') ?>" alt=""></a>
            </div>
            <div class="item-desc text-center">
                <span class="total-number">8</span>
                <span class="item-txt">items</span>
                <a href="" class="item-title">photo frames</a>
            </div>
        </div>
    </div>
</div>


<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('homepage-tab-content')->toHtml(); ?>

<?php echo $this->getLayout()->createBlock('filterproducts/new_home_list')->setProductCount(8)->setTemplate('filterproducts/best-sellers.phtml')->toHtml();?>