<?php
    $actionUrl = $this->helper('catalogSearch')->getResultUrl();
    $folded = (bool)$this->getFolded();
    $config = $this->helper('ajaxsearch')->getConfigAsJsonString(
        array('folded' => $folded, 'fullWidthMode' => !$folded)
    );
    $package = Mage::getSingleton('core/design_package')->getPackageName();
    $categoryFilter = (bool)$this->helper('ajaxsearch')->getConfig('general/show_category_filter');
?>
<form id="search_mini_form" action="<?php echo $actionUrl;?>" method="get" data-config='<?php echo $config;?>' class="<?php echo $package; ?><?php if ($folded): ?> folded<?php endif; ?>"<?php if ($categoryFilter):?> data-chosen-no-result='<?php echo $this->__('No results match'); ?>'<?php endif; ?>>
    <fieldset>
        <div class="mini-search form-search">
            <div id="searchajaxico" class=""></div>
            <?php if ($folded): ?>
            <div class="search-field-wrapper<?php echo $categoryFilter ? ' with-filter' : '' ?>">
            <?php endif; ?>
            <?php if ($categoryFilter) : ?>
                <?php echo $this->getChildHtml('ajaxsearch_category_filter') ?>
            <?php endif; ?>
            <?php
                $searchFieldText = Mage::getStoreConfig('tm_ajaxsearch/general/searchfieldtext');

                $queryText = Mage::helper('catalogsearch')->getEscapedQueryText();
                if (!empty($queryText)) {
                    $searchFieldText = $queryText;
                }
            ?>
                <input id="search" type="text" class="input-text" name="<?php echo $this->helper('catalogSearch')->getQueryParamName() ?>" value="<?php echo $searchFieldText; ?>" placeholder="<?php echo $searchFieldText; ?>" />
            <?php if ($folded): ?>
                <a class="close search-close" href="#" title="Close">×</a>
            </div>
            <?php endif; ?>
        </div>
    </fieldset>
</form>
