<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Best Home Décor &amp; Furniture Accessories in Kerala Shopping Cart  | Stories Homes</title>
    <link href="<?php echo $this->getSkinUrl('stories_new/images/favicon.png') ?>" rel="shortcut icon"/>
    <link href="<?php echo $this->getSkinUrl('stories_new/css/bootstrap.min.css') ?>" rel="stylesheet">
    <link href="<?php echo $this->getSkinUrl('stories_new/css/main.css') ?>" rel="stylesheet">
    <link href="<?php echo $this->getSkinUrl('stories_new/fonts/font.css') ?>" rel="stylesheet">

    <!--[if lt IE 9]>
    <script src="<?php echo $this->getSkinUrl('stories_new/js/html5shiv.min.js') ?>"></script>
    <script src="<?php echo $this->getSkinUrl('stories_new/js/respond.min.js') ?>"></script>
    <![endif]-->
</head>
<body>


<!-- Mobile Drop -->
<section id="mobile_dropdown">
    <div class="close_mob"><a class="mtoggle"><img src="<?php echo $this->getSkinUrl('stories_new/images/close3.png') ?>"></a><div class="clearfix"></div></div>
    <div id="mobile_drop_fix">

        <div  id="accordion1">

            <div class="panel menu_li_a arrow_me">
                <!-- Furniture -->
                <a data-toggle="collapse" data-parent="#accordion1" href="#furniture1">Furniture</a>
                <div id="furniture1" class="panel-collapse collapse">
                    <div class="panel-group menu_ma1" id="accordion21">
                        <div class="panel arrow_me">
                            <a data-toggle="collapse" data-parent="#accordion21" href="#f1">Sofa</a>
                            <div id="f1" class="panel-collapse collapse">
                                <div class="panel-body menu_ma1_sub">
                                    <a href="#">1 Seater</a>
                                    <a href="#">2 Seater</a>
                                    <a href="#">3 Seater</a>
                                    <a href="#">4 Seater</a>
                                    <a href="#">Sofa Set</a>
                                    <a href="#">Sofa cum Bed</a>
                                    <a href="#">Recliner</a>
                                    <a href="#">Telephone sofa</a>
                                </div>
                            </div>
                        </div>
                        <div class="panel arrow_me">
                            <a data-toggle="collapse" data-parent="#accordion21" href="#f2">Seating</a>
                            <div id="f2" class="panel-collapse collapse">
                                <div class="panel-body menu_ma1_sub">
                                    <a href="#">Arm Chair</a>
                                    <a href="#">Arm Less Chair</a>
                                    <a href="#">Easy Chair</a>
                                    <a href="#">Foldable Chair</a>
                                    <a href="#">Metallic Chair</a>
                                    <a href="#">Bench</a>
                                    <a href="#">Divan</a>
                                    <a href="#">Rock Chair</a>
                                </div>
                            </div>
                        </div>

                        <div class="panel arrow_me">
                            <a data-toggle="collapse" data-parent="#accordion21" href="#f3">Bedroom</a>
                            <div id="f3" class="panel-collapse collapse">
                                <div class="panel-body menu_ma1_sub">
                                    <a href="#">Cot</a>
                                    <a href="#">Bed Side Table</a>
                                    <a href="#">Dresser</a>
                                    <a href="#">Wardrobe</a>
                                    <a href="#">Bed Room Set</a>
                                    <a href="#">Kids Bed Set</a>
                                    <a href="#">Bedroom Sets</a>
                                </div>
                            </div>
                        </div>

                        <div class="panel arrow_me">
                            <a data-toggle="collapse" data-parent="#accordion21" href="#f4">Dining</a>
                            <div id="f4" class="panel-collapse collapse">
                                <div class="panel-body menu_ma1_sub">
                                    <a href="#">Chair</a>
                                    <a href="#">Table</a>
                                    <a href="#">Dining Set</a>
                                    <a href="#">Pantry Unit</a>
                                    <a href="#">Extendable/Foldable Table</a>
                                </div>
                            </div>
                        </div>

                        <div class="panel arrow_me">
                            <a data-toggle="collapse" data-parent="#accordion21" href="#f5">Study & Office</a>
                            <div id="f5" class="panel-collapse collapse">
                                <div class="panel-body menu_ma1_sub">
                                    <a href="#">Study Table</a>
                                    <a href="#">Computer Table</a>
                                    <a href="#">Book Shelf</a>
                                    <a href="#">Discussion Chair</a>
                                    <a href="#">Discussion Table</a>
                                </div>
                            </div>
                        </div>

                        <div class="panel arrow_me">
                            <a data-toggle="collapse" data-parent="#accordion21" href="#f6">Home Decore</a>
                            <div id="f6" class="panel-collapse collapse">
                                <div class="panel-body menu_ma1_sub">
                                    <a href="#">Console</a>
                                    <a href="#">Chest of Drawers</a>
                                    <a href="#">Crockery</a>
                                    <a href="#">Display Cabinet</a>
                                    <a href="#">Divider</a>
                                    <a href="#">Divder Shelf</a>
                                    <a href="#">Corner Shelf</a>
                                    <a href="#">Magazine Rack</a>
                                </div>
                            </div>
                        </div>

                        <div class="panel arrow_me">
                            <a data-toggle="collapse" data-parent="#accordion21" href="#f7">Coffee & Loveset</a>
                            <div id="f7" class="panel-collapse collapse">
                                <div class="panel-body menu_ma1_sub">
                                    <a href="#">Chair</a>
                                    <a href="#">Table</a>
                                    <a href="#">Set</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <div class="panel menu_li_a arrow_me">
                <!-- Accessories -->
                <a data-toggle="collapse" data-parent="#accordion1" href="#accessories">Accessories</a>
                <div id="accessories" class="panel-collapse collapse">
                    <div class="panel-group menu_ma1" id="accordion2">
                        <div class="panel arrow_me">
                            <a data-toggle="collapse" data-parent="#accordion2" href="#acc1">Home Decore</a>
                            <div id="acc1" class="panel-collapse collapse">
                                <div class="panel-body menu_ma1_sub">
                                    <a href="#">Vase</a>
                                    <a href="#">Candle Stand</a>
                                    <a href="#">Painting</a>
                                    <a href="#">Clock</a>
                                    <a href="#">Planter & Tree</a>
                                    <a href="#">Mirror</a>
                                    <a href="#">Tray</a>
                                    <a href="#">Showpiece</a>
                                </div>
                            </div>
                        </div>
                        <div class="panel arrow_me">
                            <a data-toggle="collapse" data-parent="#accordion2" href="#acc2">Kitchen</a>
                            <div id="acc2" class="panel-collapse collapse">
                                <div class="panel-body menu_ma1_sub">
                                    <a href="#">Cruet Set</a>
                                    <a href="#">Container</a>
                                    <a href="#">Jug</a>
                                    <a href="#">Canister Set</a>
                                    <a href="#">Bowl</a>
                                    <a href="#">Cup</a>
                                    <a href="#">Coffee Set</a>
                                    <a href="#">Kitchen Apron</a>
                                </div>
                            </div>
                        </div>

                        <div class="panel arrow_me">
                            <a data-toggle="collapse" data-parent="#accordion2" href="#acc3">Personal care</a>
                            <div id="acc3" class="panel-collapse collapse">
                                <div class="panel-body menu_ma1_sub">
                                    <a href="#">Housekeeping</a>
                                    <a href="#">Broom Holder</a>
                                    <a href="#">Laundry Basket</a>
                                    <a href="#">Storage Basket</a>
                                    <a href="#">Step Ladder</a>
                                    <a href="#">Baby Basket</a>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

            </div>


            <!-- Furnish -->
            <div class="panel menu_li_a arrow_me">
                <a data-toggle="collapse" data-parent="#accordion1" href="#furnish">Furnish</a>
                <div id="furnish" class="panel-collapse collapse">
                    <div class="panel-group menu_ma1" id="accordion3">
                        <div class="panel"><a href="#">Rug</a></div>
                        <div class="panel"><a href="#">Bed Sheet</a></div>
                        <div class="panel"><a href="#">Blankets</a></div>
                        <div class="panel"><a href="#">Curtain</a></div>
                        <div class="panel"><a href="#">Pillow & Pillow Cover</a></div>
                        <div class="panel"><a href="#">Bathmat</a></div>
                        <div class="panel"><a href="#">Runner</a></div>
                        <div class="panel"><a href="#">Throw</a></div>
                        <div class="panel"><a href="#">Bedspread</a></div>
                        <div class="panel"><a href="#">Table Mat</a></div>
                        <div class="panel"><a href="#">Quilt</a></div>
                        <div class="panel"><a href="#">Door Mat</a></div>
                        <div class="panel"><a href="#">Mattress</a></div>
                    </div>
                </div>
            </div>



            <!-- Light -->
            <div class="panel menu_li_a arrow_me">
                <a data-toggle="collapse" data-parent="#accordion1" href="#light">Light</a>
                <div id="light" class="panel-collapse collapse">
                    <div class="panel-group menu_ma1" id="accordion4">
                        <div class="panel"><a href="#">Bed Lamp</a></div>
                        <div class="panel"><a href="#">Floor Lamp</a></div>
                        <div class="panel"><a href="#">Ceiling Lamp</a></div>
                        <div class="panel"><a href="#">Table Lamp</a></div>
                        <div class="panel"><a href="#">Hanging Lamp</a></div>

                    </div>
                </div>
            </div>


            <div class="panel menu_li_a"><a  href="#">Carpet</a></div>
            <div class="panel menu_li_a"><a  href="#">Photo Frame</a></div>
            <div class="panel menu_li_a"><a  href="#">About Us</a></div>
            <div class="panel menu_li_a"><a  href="#">Contact Us</a></div>
            <div class="panel menu_li_a"><a  href="#">Privacy Policy</a></div>
            <div class="panel menu_li_a"><a href="#">Careers</a></div>
            <div class="panel menu_li_a"><a  href="#">Blog</a></div>
            <div class="panel menu_li_a"><a  href="#">How We Work</a></div>
            <div class="panel menu_li_a"><a  href="#">Safe & Secure Shopping</a></div>
            <div class="panel menu_li_a"><a  href="#">Terms of Services</a></div>
        </div>

    </div>



</section>





<!-- Main Logo -->
<section id="main_logo_part">
    <div id="main_logopart_fix">
        <div id="main_logo"><a href="#"><img src="<?php echo $this->getSkinUrl('stories_new/images/stories.jpg') ?>"></a></div>
        <div id="menu_main"><a onClick="openNav2()"><img src="<?php echo $this->getSkinUrl('stories_new/images/menu.png') ?>"></a></div>
        <div id="search_part"><a  onclick="openNav()"><img src="<?php echo $this->getSkinUrl('stories_new/images/search.png') ?>"></a></div>
        <div class="clearfix"></div>
    </div>
</section>

<!-- Search Popup -->
<div id="myNav" class="overlay">
    <a href="javascript:void(0)" class="closebtn" onClick="closeNav()"><img src="<?php echo $this->getSkinUrl('stories_new/images/close.png') ?>"></a>
    <div class="search_content">
        <div id="search_area">
            <form>
                <input type="text" name="textfield" id="textfield" class="search_field" value="What are you looking for?">
                <input type="submit" name="button" id="button" value="" class="search_btn">
            </form>
        </div>

        <div id="may_we">
            <span class="head7">May we suggest?</span>
            <a href="#">#Furnitures</a><a href="#">#Dining</a><a href="#">#Bedrooms</a><a href="#">#Seating</a><a href="#">#Bedlamp</a><a href="#">#Home Decore</a><a href="#">#Personal Care</a><a href="#">#Coffee & Loveset</a><a href="#">#Sofa</a><a href="#">#Table mat</a>
        </div>
    </div>
</div>


<!-- Menu Popup -->
<div id="myNav2" class="overlay2">
    <a href="javascript:void(0)" class="closebtn" onClick="closeNav2()"><img src="<?php echo $this->getSkinUrl('stories_new/images/close2.png') ?>"></a>
    <div class="menu_content">

        <div id="logo_menu_popup"><img src="<?php echo $this->getSkinUrl('stories_new/images/stories.jpg') ?>"></div>
        <div id="popup_menu_item">
            <a href="#">Home</a>
            <a href="#">About us</a>
            <a href="#">Contact us </a>
            <a href="#">Support </a>
            <a href="#">Privacy policy</a>
            <a href="#">Careers</a>
            <a href="#">Blog</a>
            <a href="#">How we work </a>
            <a href="#">Safe & Secure Shopping </a>
            <a href="#">Terms of service</a>
        </div>
        <div class="clearfix"></div>
        <div id="copy_menu">Copyright 2018 <span>Stories Homes furniture Store.</span> All Rights Reserved</div>

    </div>
</div>



<!-- Header Part -->
<section id="header_part">


    <!-- Logo Mobile -->
    <div id="logo_mob"><a href="#"><img src="<?php echo $this->getSkinUrl('stories_new/images/stories.jpg') ?>"></a></div>

    <div id="mob_menu"><a class="mtoggle"><img src="<?php echo $this->getSkinUrl('stories_new/images/menu.png') ?>"></a></div>
    <div id="mob_search"><a  onclick="openNav()"><img src="<?php echo $this->getSkinUrl('stories_new/images/search.png') ?>"></a></div>

    <div id="contact_top"><span>Contact  -  </span>1800 833 6660</div>
    <div id="cart_bag">
        <img src="<?php echo $this->getSkinUrl('stories_new/images/cart.png') ?>"><a href="#" class="cart_no"><span>3</span></a>

        <div class="cart_drop">
            <div class="cart_drop_fix">
                <ul>
                    <li>
                        <div class="ca_drop_img"><img src="<?php echo $this->getSkinUrl('stories_new/images/cart1_img.jpg') ?>"></div>
                        <div class="ca_drop_txt"><a href="#">Join Chair Armless<span>Rs. 10.600</span></a></div>
                        <div class="ca_drop_close"><a href="#"><img src="<?php echo $this->getSkinUrl('stories_new/images/close3.png') ?>"></a></div>
                        <div class="clearfix"></div>
                    </li>

                    <li>
                        <div class="ca_drop_img"><img src="images/cart2_img.jpg"></div>
                        <div class="ca_drop_txt"><a href="#">Dining chair armless with cushion<span>Rs. 8,800</span></a></div>
                        <div class="ca_drop_close"><a href="#"><img src="images/close3.png"></a></div>
                        <div class="clearfix"></div>
                    </li>
                    <li>
                        <div class="ca_drop_img"><img src="images/cart3_img.jpg"></div>
                        <div class="ca_drop_txt"><a href="#">Sofa O 2 Seater<span>Rs. 24,200</span></a></div>
                        <div class="ca_drop_close"><a href="#"><img src="images/close3.png"></a></div>
                        <div class="clearfix"></div>
                    </li>
                </ul>

                <div id="cart_drop_btn">
                    <a href="#" class="viewcart_drop">View Cart</a>
                    <a href="#" class="checkout_drop">Check Out</a>
                    <div class="clearfix"></div>
                </div>

            </div>
        </div>

    </div>

    <div id="logreg_icon">
        <a href="#"><img src="images/profile.png"></a>
        <div class="logreg_drop">
            <div class="logreg_drop_fix">
                <a href="#">Login</a>
                <a href="#">Register</a>
            </div>
        </div>
    </div>

    <div id="main_menu">
        <ul class="main_menu_list">

            <!-- Furniture -->
            <li class="dropdown_drop">
                <a href="#" class="drop_arrow">Furniture</a>
                <div class="dropdown-content">
                    <div class="drop_down_fix">
                        <ul id="drop_items">
                            <li>
                                <span>Sofa</span>
                                <a href="#">1 Seater</a>
                                <a href="#">2 Seater</a>
                                <a href="#">3 Seater</a>
                                <a href="#">4 Seater</a>
                                <a href="#">Sofa Set</a>
                                <a href="#">Sofa cum Bed</a>
                                <a href="#">Recliner</a>
                                <a href="#">Telephone sofa</a>
                            </li>

                            <li>
                                <span>Seating</span>
                                <a href="#">Arm Chair</a>
                                <a href="#">Arm Less Chair</a>
                                <a href="#">Easy Chair</a>
                                <a href="#">Foldable Chair</a>
                                <a href="#">Metallic Chair</a>
                                <a href="#">Bench</a>
                                <a href="#">Divan</a>
                                <a href="#">Rock Chair</a>
                            </li>

                            <li>
                                <span>Bedroom</span>
                                <a href="#">Cot</a>
                                <a href="#">Bed Side Table</a>
                                <a href="#">Dresser</a>
                                <a href="#">Wardrobe</a>
                                <a href="#">Bed Room Set</a>
                                <a href="#">Kids Bed Set</a>
                                <a href="#">Bedroom Sets</a>
                            </li>

                            <li>
                                <span>Dining</span>
                                <a href="#">Chair</a>
                                <a href="#">Table</a>
                                <a href="#">Dining Set</a>
                                <a href="#">Pantry Unit</a>
                                <a href="#">Extendable/Foldable Table</a>
                            </li>

                            <li>
                                <span>STUDY AND OFFICE</span>
                                <a href="#">Study Table</a>
                                <a href="#">Computer Table</a>
                                <a href="#">Book Shelf</a>
                                <a href="#">Discussion Chair</a>
                                <a href="#">Discussion Table</a>
                            </li>

                            <li>
                                <span>HOME DECOR</span>
                                <a href="#">Console</a>
                                <a href="#">Chest of Drawers</a>
                                <a href="#">Crockery</a>
                                <a href="#">Display Cabinet</a>
                                <a href="#">Divider</a>
                                <a href="#">Divder Shelf</a>
                                <a href="#">Corner Shelf</a>
                                <a href="#">Magazine Rack</a>
                            </li>

                            <li>
                                <span>COFFEE & LOVE SET</span>
                                <a href="#">Chair</a>
                                <a href="#">Table</a>
                                <a href="#">Set</a>
                            </li>

                        </ul>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </li>


            <!-- Accessories -->
            <li class="dropdown_drop">
                <a href="#" class="drop_arrow">Accessories</a>
                <div class="dropdown-content">
                    <div class="drop_down_fix">
                        <ul id="drop_items">
                            <li>
                                <span>HOME DECOR</span>
                                <a href="#">Vase</a>
                                <a href="#">Candle Stand</a>
                                <a href="#">Painting</a>
                                <a href="#">Clock</a>
                                <a href="#">Planter & Tree</a>
                                <a href="#">Mirror</a>
                                <a href="#">Tray</a>
                                <a href="#">Showpiece</a>
                            </li>

                            <li>
                                <span>KITCHEN</span>
                                <a href="#">Cruet Set</a>
                                <a href="#">Container</a>
                                <a href="#">Jug</a>
                                <a href="#">Canister Set</a>
                                <a href="#">Bowl</a>
                                <a href="#">Cup</a>
                                <a href="#">Coffee Set</a>
                                <a href="#">Kitchen Apron</a>
                            </li>

                            <li>
                                <span>PERSONAL CARE</span>
                                <a href="#">Housekeeping</a>
                                <a href="#">Broom Holder</a>
                                <a href="#">Laundry Basket</a>
                                <a href="#">Storage Basket</a>
                                <a href="#">Step Ladder</a>
                                <a href="#">Baby Basket</a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </li>


            <!-- Furnish -->
            <li class="dropdown_drop">
                <a href="#" class="drop_arrow">Furnish</a>
                <div class="dropdown-content">
                    <div class="drop_down_fix">
                        <ul id="drop_items">
                            <li><a href="#">Rug</a></li>
                            <li><a href="#">Bed Sheet</a></li>
                            <li><a href="#">Blankets</a></li>
                            <li><a href="#">Curtain</a></li>
                            <li><a href="#">Pillow & Pillow Cover</a></li>
                            <li><a href="#">Bathmat</a></li>
                            <li><a href="#">Runner</a></li>
                            <li><a href="#">Throw</a></li>
                            <li><a href="#">Bedspread</a></li>
                            <li><a href="#">Table Mat</a></li>
                            <li><a href="#">Quilt</a></li>
                            <li><a href="#">Door Mat</a></li>
                            <li><a href="#">Mattress</a></li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </li>


            <!-- Light -->
            <li class="dropdown_drop">
                <a href="#" class="drop_arrow">Light</a>
                <div class="dropdown-content">
                    <div class="drop_down_fix">
                        <ul id="drop_items">
                            <li><a href="#">Bed Lamp</a></li>
                            <li><a href="#">Floor Lamp</a></li>
                            <li><a href="#">Ceiling Lamp</a></li>
                            <li><a href="#">Table Lamp</a></li>
                            <li><a href="#">Hanging Lamp</a></li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </li>


            <!-- Carpet -->
            <li class="dropdown_drop"><a href="#" class="drop_arrow">Carpet</a></li>


            <!-- Photo Frame -->
            <li class="dropdown_drop"><a href="#" class="drop_arrow">Photo Frame</a></li>

        </ul>
    </div>
    <div class="clearfix"></div>
</section>



<!-- Banner Part -->
<section id="banner_slider">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>

        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active"><img src="images/banner1.jpg" class="banner_res"></div>
            <div class="item"><img src="images/banner2.jpg" class="banner_res"></div>
            <div class="item"><img src="images/banner3.jpg" class="banner_res"></div>
        </div>
    </div>
</section>



<!-- Dsigners from 19 countries -->
<section id="countries_part">
    <div id="countries_right_bg"></div>
    <div id="countries_fix">
        <div id="main_head_part">
            One is Equal to 19</span>
            <div id="mainhead_sub"><p style="visibility:hidden">Welcome to complete global home concepts</p></div>
        </div>

        <div class="country_txt">Stories projects, the project management division under Stories Global Home Concepts, a Bronet Group of company, we bring global expertise on large scale projects for any industry through our international partners. Stories Projects is all about comfort, elegance and quality. </div>
        <div class="county_img1"><img src="images/chair.png"></div>
        <div class="readmore2"><a href="digital_brochure.pdf" target="_blank">Read More</a></div>
        <div class="clearfix"></div>
    </div>

</section>


<!-- Product Listing Part -->
<section id="product_listing_part">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div id="product_list_fix">
                    <div id="product_head">
                        Explore <br><span>our products</span>
                    </div>

                    <div class="grid_panel">
                        <div class="pro_items">
                            <a href="#">
                                <img src="images/product_home1.jpg" class="img-responsive">
                                <span class="head2">Furniture</span>
                                728 Items
                            </a>
                        </div>
                    </div>

                    <div class="grid_panel">
                        <div class="pro_items">
                            <a href="#">
                                <img src="images/product_home2.jpg" class="img-responsive">
                                <span class="head2">Accessories</span>
                                1664 Items
                            </a>
                        </div>
                    </div>


                    <div class="grid_panel">
                        <div class="pro_items">
                            <a href="#">
                                <img src="images/product_home3.jpg" class="img-responsive">
                                <span class="head2">Furnish</span>
                                338 Items
                            </a>
                        </div>
                    </div>

                    <div class="grid_panel">
                        <div class="pro_items">
                            <a href="#">
                                <img src="images/product_home4.jpg" class="img-responsive">
                                <span class="head2">Photo Frame</span>
                                70 Items
                            </a>
                        </div>
                    </div>

                    <div class="grid_panel">
                        <div class="pro_items">
                            <a href="#">
                                <img src="images/product_home5.jpg" class="img-responsive">
                                <span class="head2">Lights</span>
                                90 Items
                            </a>
                        </div>
                    </div>


                    <div class="grid_panel">
                        <div class="pro_items">
                            <a href="#">
                                <img src="images/product_home6.jpg" class="img-responsive">
                                <span class="head2">Carpets</span>
                                65 Items
                            </a>
                        </div>
                    </div>


                    <div class="grid_panel">
                        <div class="pro_items2">
                            <a href="#">
                                <img src="images/icon1.png">
                                <span>View All Products</span>
                                <img src="images/icon2.png">
                            </a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>


<!-- Stories Projects -->
<section id="stories_projects">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div id="project_fix">
                    <div class="project_img"><img src="images/project_bg.png"></div>
                    <div class="project_txt">
                        <span class="head8">STORIES <span>PROJECTS</span></span>
                        We offer classiest furniture from around the world that can guarantee maximum luxury, high durability and stunning beauty while adhering to specifications provided by the client to the hilt.

                        <div class="readmore3"><a href="#">Read More</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<!-- About -->
<section id="about_us">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div id="about_fix">
                    <div id="about_left">
                        Our <span>Story</span>
                    </div>
                    <div id="about_right">
                        <span>About Us</span>
                        Stories is a lifestyle destination. It caters to the furniture needs of a customer purely from the point of view of delivering decor solutions for the home at large, thereby adopting a far more holistic approach as opposed to a regular ‘furniture store’. This forms the essence of Stories brand philosophy.
                        <div class="readmore"><a href="#">Read More</a></div>


                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</section>




<!-- Blog Head -->
<div id="blog_head">
    <div id="blog_head_fix">
        <div class="blog_headleft">Marketing Campaigns</div>
        <div class="blog_headright"><a href="#">Read More</a></div>
        <div class="clearfix"></div>
    </div>
</div>


<!-- Blog Contents -->
<section id="blog_content">
    <div class="container">

        <div class="container_fix">
            <div class="row">
                <div class="col-md-3 col-sm-3 col-xs-12">
                    <div class="blog_items">
                        <div class="blog_img"><a href="https://www.youtube.com/watch?v=aDZe0lB3Osw" target="_blank"><img src="images/blog_img1.jpg" class="img-responsive "></a></div>
                        <div class="blog_txt">
                            <span class="head6">Brand Message Launched</span>
                            Stories Global Home Concepts, South India's largest lifestyle destination, will soon enter the Kochi market.

                            <div class="readmore"><a href="https://www.youtube.com/watch?v=aDZe0lB3Osw" target="_blank">Read More</a></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                    <div class="blog_items">
                        <div class="blog_img"><a href="https://www.facebook.com/storieshomes/videos/2555627457995031/" target="_blank"><img src="images/blog_img2.jpg" class="img-responsive "></a></div>
                        <div class="blog_txt">
                            <span class="head6">Brand Message Video Goes Viral</span>
                            The brand message video of Stories Global Home Concepts, South India's largest lifestyle destination, has gone viral in the social media with more than one million people watching it in the first 24 hours.

                            <div class="readmore"><a href="https://www.facebook.com/storieshomes/videos/2555627457995031/" target="_blank">Read More</a></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                    <div class="blog_items">
                        <div class="blog_img"><a href="invite.pdf" target="_blank"><img src="images/blog_img3.jpg" class="img-responsive "></a></div>
                        <div class="blog_txt">
                            <span class="head6">Stories Kochi Showroom Soft Launch</span>
                            Bollywood actor Mr. Jackie Shroff will soft launch the Kochi showroom of Stories in the presence of eminent architects of the state. The corporate profile of the brand as well as the official agreement handover of the new showroom at Pune will also be held at the venue.

                            <div class="readmore"><a href="invite.pdf" target="_blank">Read More</a></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-12">
                    <div class="blog_items">
                        <div class="blog_img"><a href="#"><img src="images/blog_img4.jpg" class="img-responsive "></a></div>
                        <div class="blog_txt">
                            <span class="head6">Stories Café to be launched soon</span>
                            First of its kind café inside a furniture showroom with a goal of providing unique conversation and inter-action platform for customers and like-minded people, Stories Global Concept will open STORIES CAFÉ inside its Kochi showroom soon. The project will be extended to all new showrooms in the coming months.

                            <!--<div class="readmore"><a href="#">Read More</a></div>-->
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>



<!-- Address Part -->
<section id="address_part">
    <div class="container">

        <div id="address_fix">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">

                    <div id="address">
                        <span class="head5">Contact Us</span>
                        <div class="clearfix"></div>
                        <div id="address_left">
                            Let’s talk.<br>Drop us a line
                            <p><a href="mailto:contact@storieshomes.com">contact@storieshomes.com</a><br>0495 - 2 433 633</p>
                        </div>
                        <div id="address_right">
                            <span>Stories Global Home Concepts</span>
                            Airport By Pass Road, Pantheerankav Junction<br>Kozhikode, Kerala - 673019
                        </div>
                        <div class="clearfix"></div>
                    </div>


                    <div id="store_locator">
                        <a href="#">
                            <span><img src="images/icon4.png"></span>Locate Our Store
                        </a>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>

    </div>
</section>

<!-- Footer Part -->
<section id="footer_part">
    <div class="container">

        <div id="footer_fix">

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">


                    <div id="menu_footer">
                        <a href="#">Home</a>
                        <a href="#">About us</a>
                        <a href="#">Contact us</a>
                        <a href="#">Support </a>
                        <a href="#">Privacy policy</a>
                        <a href="#">Careers</a>
                        <a href="#">Blog</a>
                        <a href="#">How we work</a>
                        <a href="#">Safe & Secure Shopping</a>
                        <a href="#">Terms of service</a>
                        <div class="clearfix"></div>
                    </div>


                    <div id="newsletter">
                        <span class="head3">Subscribe to the Stories Newsletter</span>
                        <div id="email_newsletter">
                            <form>
                                <input type="text" name="textfield" id="textfield" class="newsletter_field" value="Your Email Address">
                                <input type="submit" name="button" id="button" value="" class="submit_btn">
                            </form>
                            <div class="clearfix"></div>
                        </div>
                        <span class="head4">By subscribing to this bewsletter, you are agreeing to our Privacy Policy</span>
                    </div>


                    <div id="follow_part">
                        <span class="head3">Follow Us On</span>
                        <div id="social_footer">
                            <a href="#"><img src="images/facebook.png"></a>
                            <a href="#"><img src="images/twitter.png"></a>
                            <a href="#"><img src="images/google_plus.png"></a>
                            <a href="#"><img src="images/pinterest.png"></a>
                            <a href="#"><img src="images/houzz.png"></a>
                        </div>
                        <div id="copyright">
                            Copyright 2018 <span>Stories Homes furniture Store.</span> All Rights Reserved
                        </div>
                    </div>
                    <div class="clearfix"></div>

                </div>
            </div>
        </div>
    </div>
</section>


<!-- Jquery Files -->
<script src="<?php echo $this->getSkinUrl('stories_new/js/jquery.js') ?>"></script>
<script src="<?php echo $this->getSkinUrl('stories_new/js/bootstrap.min.js') ?>"></script>
<script src="<?php echo $this->getSkinUrl('stories_new/js/ui.js') ?>"></script>
<script>
    function openNav() {
        document.getElementById("myNav").style.display = "block";
    }

    function closeNav() {
        document.getElementById("myNav").style.display = "none";
    }
</script>

<script>
    function openNav2() {
        document.getElementById("myNav2").style.display = "block";
    }

    function closeNav2() {
        document.getElementById("myNav2").style.display = "none";
    }
</script>
<script src="<?php echo $this->getSkinUrl('stories_new/js/pinterest_grid.js') ?>"></script>
<script>
    $(document).ready(function() {

        $('#product_list_fix').pinterest_grid({
            no_columns: 2,
            padding_x: 0,
            padding_y: 0,
            margin_bottom: 0,
            single_column_breakpoint: 768
        });

    });
</script>
<script type="text/javascript">
    jQuery(document).ready(function($) {
        $("#mobile_dropdown").hide();
        $(".mtoggle").click(function() {
            $("#mobile_dropdown").toggle("slide",
                { direction: "right"  }, 'fast');
        });
    });
</script>

<script>
    $(function(){
        $('.carousel').carousel({
            interval: 3000,
            pause: "false"
        });
    });
</script>
</body>
</html>