<?php

if(!$this->getConfig('enabled')) return;
?>
<?php if(!count($this->getItemCollection()->getItems())) return; ?>
<?php
    // getConfig
    $widthImage     = $this->getConfig('widthImage') ? $this->getConfig('widthImage') : 135;
    $heightImage    = $this->getConfig('heightImage') ? $this->getConfig('heightImage') : 135;
    $price          = $this->getConfig('price');
    $cart           = $this->getConfig('cart');
    // $compare        = $this->getConfig('compare');
    // $wishlist       = $this->getConfig('wishlist');
    $review         = $this->getConfig('review');
    // $rows           = $this->getConfig('rows');
    // $class          = ($rows > 1) ? '.slide-multirows' : '.products-grid';
?>
<div class="upsellslider">
    <?php echo $this->getConfig('title') ? '<div class="bx-title"><div class="bg-title"><h2 class="title">' .$this->getConfig('title'). '</h2></div></div>' : ''; ?>
	<ul class="products-grid">
    <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): ?>
            <li class="item">
                <div class="item-inner">
		    <div class="box-images">
			<a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize($widthImage, $heightImage) ?>" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a>
		    </div>
			
			
			
			    <ul class="add-to-links">
				<?php if($cart): ?>
				    <?php if($_link->isSaleable()): ?>
					<li class="button1"><button type="button" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_link) ?>')"><span><span><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></span></span></button></li>
				    <?php else: ?>
					<li class="button1"><p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p></li>
				    <?php endif; ?>
				<?php endif; ?>
			    </ul>
			    
			
			

		    <div class="product-shop1">
				<h2 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a></h2>
				<?php if( $review ): ?>
					<?php echo $this->getReviewsSummaryHtml($_link) ?>
				<?php endif; ?>
				<?php if( $price ): ?>
					<?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
				<?php endif; ?>
			</div>
                
                
		</div>
            </li>
            <?php endif; ?>
        <?php endfor; ?>
    <?php endfor; ?>
    </ul>
</div>

<script type="text/javascript">
    jQuery(document).ready(function($){
        (function(selector){
            var $content = $(selector);
            var $slider  = $('.products-grid', $content);
            var slider   = $slider.bxSlider({
                <?php echo $this->setBxslider() ?>
                //infiniteLoop: false,
                moveSlides:1,
                slideMargin: 1,
                autoHover: true, // stop while hover <=> slider.stopAuto(); + slider.startAuto();
            })

        })(".upsellslider");
    });
</script>
