<div class="custom-menu-wrapper">
    <div class="row">
        <div class="col-xs-12 col-sm-3">
        <div class="menu-col menu-col1">
        <h3>This is Photoshop's version  of Lorem Ipsum...</h3>
        <div class="menu-custom-img"><img src="{{media url="wysiwyg/cus1.jpg"}}" alt="" /></div>
        <div class="menu-custom-des">This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet... </div>
        </div>
        </div>
        <div class="col-xs-12 col-sm-3">
        <div class="menu-col menu-col2">
        <h3>This is Photoshop's version  of Lorem Ipsum...</h3>
        <div class="menu-custom-img"><img src="{{media url="wysiwyg/cus2.jpg"}}" alt="" /></div>
        <div class="menu-custom-des">This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet... </div>
        </div>
        </div>
        <div class="col-xs-12 col-sm-3">
        <div class="menu-col menu-col3">
        <h3>This is Photoshop's version  of Lorem Ipsum...</h3>
        <div class="menu-custom-img"><img src="{{media url="wysiwyg/cus3.jpg"}}" alt="" /></div>
        <div class="menu-custom-des">This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet... </div>
        </div>
        </div>
        <div class="col-xs-12 col-sm-3">
        <div class="menu-col menu-col4">
        <h3>This is Photoshop's version  of Lorem Ipsum...</h3>
        <div class="menu-custom-img"><img src="{{media url="wysiwyg/cus4.jpg"}}" alt="" /></div>
        <div class="menu-custom-des">This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet... </div>
        </div>
        </div>
    </div>
</div>



<div class="links-bottom">
    <a href="#"><em class="fa fa-cc-discover"></em></a>
    <a href="#"><em class="fa fa-cc-paypal"></em></a>
    <a href="#"><em class="fa fa-cc-mastercard"></em></a>
    <a href="#"><em class="fa fa-cc-visa"></em></a>
    <a href="#"><em class="fa fa-cc-stripe"></em></a>
</div>




<!--footer_info-->
<div class="f-col f-col1 col-sm-3 col-md-3 col-sms-6 col-smb-12">
<div class="logo_footer">
<a href="#"><img src="http://192.168.0.113/tv_arion/media/wysiwyg/logo2.png" alt=""></a>
</div>
<div class="footer-static-content">
<p>This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin...</p>
<a class="shop-now" href="#">Get Theme !</a>
</div>
</div>
<div class="f-col f-col2 col-sm-3 col-md-3 col-sms-6 col-smb-12">
<div class="footer-title">
<h3>Contact Information</h3>
</div>
<div class="footer-static-content">
<p class="add"><em class="fa fa-map-marker"></em>75, Avenue Anatole France, Paris</p>
<p class="phone"><em class="fa fa-fax"></em>01.234 56789 - 10.987 65432</p>
<p class="mail"><em class="fa fa-envelope"></em>Themevast@gmail.com</p>
</div>
</div>
<div class="f-col f-col3 col-sm-3 col-md-3 col-sms-6 col-smb-12">{{block type="core/template" template="themevast/lastesttweet/lastesttweet.phtml" }}</div>
<div class="f-col f-col4 col-sm-3 col-md-3 col-sms-6 col-smb-12">
{{block type="newsletter/subscribe" name="left.newsletter" template="newsletter/subscribe.phtml"}}
<div class="footer-static-title">
<h3>connect with us</h3>
</div>
<div class="connect">
    <a class="social1" href="#" title="twitter"><span><em class="fa fa-twitter"></em></span></a>
    <a class="social2" href="#" title="skype"><span><em class="fa fa-skype"></em></span></a>
    <a class="social3" href="#" title="facebook"><span><em class="fa fa-facebook"></em></span></a>
    <a class="social4" href="#" title="google"><span><em class="fa fa-google-plus"></em></span></a>
    <a class="social5" href="#" title="vine"><span><em class="fa fa-vine"></em></span></a>
    <a class="social6" href="#" title="rss"><span><em class="fa fa-rss"></em></span></a>
</div>
</div>









<div class="banner_content_home1">
    <div class="banner-box banner1">
        <div class="box-image"><img src="{{media url="wysiwyg/stb1.jpg"}}" alt="" /></div>
    </div>
    <div class="banner-position1">
        <div class="banner-box banner2">
            <div class="box-image"><img src="{{media url="wysiwyg/stb2.jpg"}}" alt="" /></div>
            <div class="banner-des">
                <h2>The New&nbsp;<span>MacBook</span>&nbsp;Air&nbsp;<a href="#"><em class="fa fa-angle-right"></em></a></h2>
            </div>
        </div>
        <div class="banner-box banner3">
            <div class="box-image"><img src="{{media url="wysiwyg/stb3.jpg"}}" alt="" /></div>
        </div>
    </div>
    <div class="banner-box banner4">
        <div class="box-image"><img src="{{media url="wysiwyg/stb4.jpg"}}" alt="" /></div>
    </div>
</div>





<div class="banner_right_home1">
    <div class="row">
        
        <div class="col-sm-4">
            <div class="banner_right banner-1">
                <div class="title-banner">
                <div class="icon-font"><em class="fa fa-cogs"></em></div>
                <div class="banner_title">
                <h3>SUPPORT&nbsp;<span>24/7</span></h3>
                <p>We support <span>online 24 hours</span> a day</p>
                </div>
                </div>
                <div class="content_banner">This is Photoshop's version of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet.</div>
                </div>
        </div>
        <div class="col-sm-4">
            <div class="banner_right banner-2">
            <div class="title-banner">
            <div class="icon-font"><em class="fa fa-reply"></em></div>
            <div class="banner_title">
            <h3><span>FREE</span>&nbsp;return</h3>
            <p><span>30 days</span> money back guarantee!</p>
            </div>
            </div>
            <div class="content_banner">This is Photoshop's version of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet.</div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="banner_right banner-3">
            <div class="title-banner">
            <div class="icon-font"><em class="fa fa-truck"></em></div>
            <div class="banner_title">
            <h3><span>FREE</span>&nbsp;SHIPPING</h3>
            <p><span>Free&nbsp;</span>shipping on all UK order</p>
            </div>
            </div>
            <div class="content_banner">This is Photoshop's version of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet.</div>
            </div>
        </div>
    </div>
</div>



<div class="f-col f-col1 col-sm-55 col-sms-6 col-smb-12">
<div class="footer-static-title">
<h3>information</h3>
</div>
<div class="footer-static-content">
<ul>
    <li><a href="{{store direct_url="contacts"}}">Delivery Information</a></li>
    <li><a href="{{store direct_url="privacy-policy-cookie-restriction-mode"}}">Privacy Policy</a></li>
    <li><a href="{{store direct_url="contacts"}}">Discount</a></li>
    <li><a href="{{store direct_url="catalogsearch/term/popular"}}">Terms &amp; Condition</a></li>
    <li class="first"><a href="{{store direct_url="catalog/seo_sitemap/category"}}">Sitemap</a></li>
    <li><a href="{{store direct_url="privacy-policy-cookie-restriction-mode"}}">Privacy Policy</a></li>
    <li><a href="{{store direct_url="customer/account/index"}}">My Account</a></li>
    <li class="last"><a href="{{store direct_url="catalogsearch/advanced"}}">Advanced Search</a></li>
</ul>
</div>
</div>
<div class="f-col f-col2 col-sm-55 col-sms-6 col-smb-12">
<div class="footer-static-title">
<h3>our offers</h3>
</div>
<div class="footer-static-content">
<ul>
    <li class="first"><a href="{{store direct_url="catalog/seo_sitemap/category"}}">Sitemap</a></li>
    <li><a href="{{store direct_url="contacts"}}">Delivery Information</a></li>
    <li><a href="{{store direct_url="privacy-policy-cookie-restriction-mode"}}">Privacy Policy</a></li>
    <li><a href="{{store direct_url="contacts"}}">Discount</a></li>
    <li><a href="{{store direct_url="privacy-policy-cookie-restriction-mode"}}">Privacy Policy</a></li>
    <li><a href="{{store direct_url="customer/account/index"}}">My Account</a></li>
    <li><a href="{{store direct_url="contacts"}}">Discount</a></li>
    <li class="last"><a href="{{store direct_url="catalogsearch/advanced"}}">Advanced Search</a></li>
</ul>
</div>
</div>
<div class="f-col f-col3 col-sm-55 col-sms-6 col-smb-12">
<div class="footer-static-title">
<h3>our service</h3>
</div>
<div class="footer-static-content">
<ul>
    <li class="first"><a href="{{store direct_url="contacts"}}">Contact Us</a></li>
    <li><a href="{{store direct_url="contacts"}}">Discount</a></li>
    <li><a href="{{store direct_url="catalog/seo_sitemap/category"}}">Sitemap</a></li>
    <li><a href="{{store direct_url="about-magento-demo-store"}}">About us</a></li>
    <li><a href="{{store direct_url="customer-service"}}">Custom Service</a></li>
    <li><a href="{{store direct_url="contacts"}}">Contact Us</a></li>
    <li><a href="{{store direct_url="customer-service"}}">Custom Service</a></li>
    <li class="last"><a href="{{store direct_url="about-magento-demo-store"}}">About us</a></li>
</ul>
</div>
</div>
<div class="f-col f-col4 col-sm-55 col-sms-6 col-smb-12">
<div class="footer-static-title">
<h3>About Us</h3>
</div>
<div class="footer-static-content">
<ul>
    <li class="first"><a href="{{store direct_url="customer/account/index"}}">My Account</a></li>
    <li><a href="{{store direct_url="catalog/seo_sitemap/category"}}">Sitemap</a></li>
    <li><a href="{{store direct_url="contacts"}}">Contact Us</a></li>
    <li><a href="{{store direct_url="contacts"}}">Discount</a></li>
    <li><a href="{{store direct_url="catalog/seo_sitemap/category"}}">Sitemap</a></li>
    <li><a href="{{store direct_url="contacts"}}">Contact Us</a></li>
    <li><a href="{{store direct_url="customer-service"}}">Custom Service</a></li>
    <li class="last"><a href="{{store direct_url="about-magento-demo-store"}}">About us</a></li>
</ul>
</div>
</div>
<div class="f-col f-col5 col-sm-55 col-sms-6 col-smb-12">{{block type="newsletter/subscribe" name="left.newsletter" template="newsletter/subscribe.phtml"}}
<div class="footer-static-title">
<h3>connect with us</h3>
</div>
<div class="connect"><a class="social1" title="twitter" href="#"><span><em class="fa fa-twitter">&nbsp;</em></span></a> <a class="social2" title="skype" href="#"><span><em class="fa fa-skype">&nbsp;</em></span></a> <a class="social3" title="facebook" href="#"><span><em class="fa fa-facebook">&nbsp;</em></span></a> <a class="social4" title="google" href="#"><span><em class="fa fa-google-plus">&nbsp;</em></span></a> <a class="social5" title="vine" href="#"><span><em class="fa fa-vine">&nbsp;</em></span></a></div>
</div>

