<?php $_cartQty = $this->getSummaryCount() ?>
<div id ="mini_cart_block">
    <div class="block-cart mini_cart_ajax">
            <div class="block-cart">
                <?php $_cartQty = $this->getSummaryCount() ?>
          <!--<span class="top-cart-icon"></span>-->
                <div class="cart-mini-title">
                    <a class="shopping-cart" href="<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>"><i class="fa fa-shopping-cart"></i>
                    <span class="cart-title"><?php echo $this->__('My cart') ?></span>
                    
                    
                    <span class="cart-count"><?php echo $_cartQty; ?><?php if($_cartQty>1) { echo $this->__(' item (s)'); } else { echo $this->__(' item (s)'); } ?><i class="fa fa-angle-down"></i></span>
                    </a>
                </div>
                <div class="top-cart-content">
                    <?php $_items = $this->getRecentItems() ?>
                    <?php if (count($_items)): ?>
                        <ol id="cart-sidebar" class="mini-products-list">
                            <?php foreach ($_items as $_item): ?>
                                <?php echo $this->getItemHtml($_item) ?>
                            <?php endforeach; ?>
                        </ol>
                        <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
                    <?php else: ?>
                        <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
                    <?php endif ?>
                    <div class="top-subtotal"><?php echo $this->__('Subtotal') ?>: <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?></div>
                    <?php if ($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                        <div class="actions">
                            <?php echo $this->getChildHtml('extra_actions') ?>
                            <button type="button" title="<?php echo $this->__('Checkout') ?>" class="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
                        </div>
                    <?php endif ?>
                </div>
            </div>

    </div>
</div>
<script type="text/javascript">
    var ajaxCartCfg = {
        'removeConfirm' : '<?php echo $this-> __('Are you sure you would like to remove this item ?') ?>',
    };
</script>
