<div class="container">
        <div class="large_image_area">
            <div class="img-detail">
                <p>furniture by designers from 19 countries, under one roof. Now on 100 feet road, indiranagar, bangalore.</p>
            </div>
            <div class="img_holder"><img class="img-responsive" src="<?php echo $this->getSkinUrl('images/large_img.jpg') ?>" alt=""></div>
        </div>
        <div class="form_cont">
            <p>fill in your details to get a free voucher worth</p>
            <span class="price_txt">₹1,500*</span>
            <form name="campaignForm" method="post" class="form-horizontal" data-toggle="validator" role="form" action="<?php echo $this->getUrl('emailerCampaign/index/post') ?>">
                <div class="form-group">
                    <label for="inputName" class="col-sm-2 control-label">Name</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="inputName" name="name" placeholder="Name" value="" required/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="inputEmail" name="email" placeholder="Email" value="" required/>
                    </div>
                    <div class="help-block with-errors"></div>
                </div>
                <div class="form-group">
                    <label for="inputTel" class="col-sm-2 control-label">Phone</label>
                    <div class="col-sm-10">
                        <input type="text" id="inputTel" name="phone" class="form-control mobile-number" placeholder="e.g. +1 702 123 4567" value="" required/>
                    </div>
                    <div class="help-block with-errors"></div>
                </div>
                <div class="form-group clearfix">
                    <div class="col-sm-6 pull-right">
                        <button type="submit" class="form-control" id="">grab now</button>
                    </div>
                </div>
            </form>
            <span class="condition_txt clearfix">*conditions apply</span>
        </div>
    <?php echo $this->getLayout()->createBlock('testimonial/testimonial')->setTemplate('testimonial/testimonial1.phtml')->toHtml() ?>
    <?php echo $this->getLayout()->createBlock('bannerpro/bannerpro')->setTemplate('bannerpro/bannerpro.phtml')->toHtml(); ?>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_partner_logos')->toHtml(); ?>
</div>

<script type="text/javascript">
    //$(".mobile-number").intlTelInput();
</script>


