<?php
$_coreHelper = Mage::helper('core');
$_helper = $this->helper('catalog/output');
$_image_helper = $this->helper('catalog/image');
$productCollection = $this->_getProductCollection();
?>
<!-- new arrival container -->
<?php if (!$productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="container">
        <div class="new-arrival-cont">
            <h2><?php echo $this->__('New Arrival') ?></h2>
            <div id="carousel" class="owl-carousel owl-theme">
                <?php foreach ($productCollection as $product): ?>
                    <div class="item">
                        <div class="product-box text-center">
                            <div class="img-holder">
                                <a href="<?php echo $product->getProductUrl() ?>"
                                   title="<?php echo $this->stripTags($this->getImageLabel($product, 'thumbnail'), null, true) ?>"
                                   class="img-responsive">
                                    <img src="<?php echo $_image_helper->init($product, 'thumbnail')->resize(250); ?>"
                                         alt="<?php echo $this->stripTags($this->getImageLabel($product, 'thumbnail'), null, true) ?>"/>
                                </a>
                            </div>
                            <div class="product-desc">
                                <a class="product-title" href="<?php echo $product->getProductUrl() ?>"
                                   title="<?php echo $this->stripTags($product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($product, $product->getName(), 'name') ?></a>
                                <span class="product-price">
                                <?php if ($product->getSpecialPrice() > 0): ?>
                                    <div class="price-box">
                                        <p class="old-price">
                                            <span class="price"
                                                  id="old-price-<?php echo $product->getId() ?>"><?php echo $_coreHelper->currency($product->getPrice()) ?></span>
                                        </p>
                                        <p class="special-price">
                                            <span class="price"
                                                  id="product-price-<?php echo $product->getId() ?>"><?php echo $_coreHelper->currency($product->getSpecialPrice()); ?></span>
                                        </p>
                                    </div>
                                <?php else: ?>
                                    <div class="price-box">
                                        <span class="price">
                                            <?php echo $_coreHelper->formatPrice($product['price'], false) ?>
                                        </span>
                                    </div>
                                <?php endif; ?>
                        </span>
                            </div>
                            <div class="overlay"></div>
                            <div class="buy-now-btn">
                                <?php if ($product->isSaleable()): ?>
                                    <a href="<?php echo $product->getProductUrl() ?>" class="product-price"
                                       title="<?php echo $this->__('Buy Now') ?>">
                                        <span>&nbsp<?php echo $this->__('Buy Now') ?></span>
                                    </a>
                                <?php else: ?>
                                    <a href="javascript:void(0)" class="product-price"
                                       title="<?php echo $this->__('Out of stock') ?>">
                                        <span>&nbsp<?php echo $this->__('Out of stock') ?></span>
                                    </a>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>