<?php
$_coreHelper = Mage::helper('core');
$store = Mage::app()->getStore();
$code = $store->getCode();
$category = new Mage_Catalog_Model_Category();
$category->load(193);
$_productCollection = $category->getProductCollection();
$_productCollection->addAttributeToSelect('*');
$_helper = $this->helper('catalog/output');
$_image_helper = $this->helper('catalog/image');
?>

    <!-- new arrival container -->
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="container">
    <div class="new-arrival-cont">
        <h2>new arrival</h2>

        <div id="carousel" class="owl-carousel owl-theme">
            <?php $i = 0;
            foreach ($_productCollection as $_product):
            $product = $_product; ?>
            <div class="item">
                <div class="product-box text-center">
                    <div class="img-holder">
                       <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($product, 'thumbnail'), null, true) ?>" class="img-responsive">
                                <img src="<?php echo $_image_helper->init($product, 'thumbnail')->resize(275); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($product, 'thumbnail'), null, true) ?>"/>
                            </a>
                    </div>
                    <div class="product-desc">
                        <a class="product-title" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>

                        <span class="product-price">
                                <?php if ($_product->getSpecialPrice() > 0): ?>
                                    <div class="price-box">
                                        <p class="old-price">
                                            <span class="price" id="old-price-<?php echo $_product->getId() ?>"><?php echo $_coreHelper->currency($_product->getPrice()) ?></span>
                                        </p>
                                        <p class="special-price">
                                            <span class="price" id="product-price-<?php echo $_product->getId() ?>"><?php echo $_coreHelper->currency($_product->getSpecialPrice()); ?></span>
                                        </p>
                                    </div>
                                <?php else: ?>
                                    <div class="price-box">
                                        <span class="price">
                                            <?php echo $_coreHelper->formatPrice($_product['price'], false) ?>
                                        </span>
                                    </div>
                                <?php endif; ?>
                        </span>
                    </div>
                    <div class="overlay"></div>
                    <div class="buy-now-btn">
                    <?php if($_product->isSaleable()): ?>
                       <a href="<?php echo $product->getProductUrl() ?>" class="product-price" title="<?php echo $this->__('Buy Now') ?>">
                                <span>&nbsp<?php echo $this->__('Buy Now') ?></span>
                            </a>
                    <?php else: ?>
                        <a href="javascript:void(0)" class="product-price" title="<?php echo $this->__('Out of stock') ?>">
                                <span>&nbsp<?php echo $this->__('Out of stock') ?></span>
                            </a>
                    <?php endif; ?>
                    </div>
                </div>
            </div>
            <?php $i++; ?>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<?php endif; ?>