<div class="mini-cart">
    <?php
        $store = Mage::app()->getStore();
        $code  = $store->getCode();
        $display_subtotal_price = Mage::getStoreConfig("tax/cart_display/subtotal", $code);
    ?>
    <?php $_cartQty = $this->getSummaryCount(); ?>
    <?php
        if(!$_cartQty) $_cartQty = 0;
        $_subtotal = $this->helper('checkout')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal())
    ?>
    <?php $_items = $this->getRecentItems() ?>

        <div class="cart-icon">
            <a href="javascript:void(0)" class="mybag-link">
                <span class="total-products"><?php echo $_cartQty ?></span>
            </a>
        </div>


    <div class="topCartContent">
        <div class="inner-wrapper"><?php /*extra div to smooth slideUp and slideDown*/ ?>
            <?php $_items = $this->getRecentItems() ?>
            <?php if(count($_items)): ?>
                <ol class="mini-products-list">
                    <?php foreach($_items as $_item): ?>
                        <?php echo $this->getItemHtml($_item) ?>
                    <?php endforeach; ?>
                </ol>
                <div class="totals">
                    <span class="label"><?php echo $this->__('Total')?>: </span>
                    <span class="price-total"><?php echo $_subtotal ?></span>
                </div>
                <div class="actions">
                    <a class="btn btn-sm btn-default" href="<?php echo $this->getUrl('checkout/cart'); ?>"><i class="icon-basket"></i><?php echo $this->__('View Cart') ?></a>
                    <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                        <a class="btn btn-sm btn-primary" href="<?php echo $this->getCheckoutUrl(); ?>"><i class="icon-right-thin"></i><?php echo $this->__('Bill Now') ?></a>
                    <?php endif; ?>
                    <div class="clearer"></div>
                </div>
            <?php else: ?>
                <p class="cart-empty">
                    <?php echo $this->__('You have no items in your shopping cart.'); ?>
                </p>
            <?php endif; ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    jQuery(function($){
        $('.mini-cart').mouseover(function(e){
            $(this).children('.topCartContent').fadeIn(200);
            return false;
        }).mouseleave(function(e){
            $(this).children('.topCartContent').fadeOut(200);
            return false;
        });
    });
</script>