<?php

if(!$this->getConfig('enabled')) return;

$_productCollection=$this->getProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php
    $helpLabels = $this->helper('themevast/labels');
?>
<div class="featuredproduct">
	
	<?php echo $this->getConfig('title') ? '<div class="featured-title bx-title"><div class="bg-title"><h2 class="title">' .$this->getConfig('title'). '</h2></div></div>' : '';
	if(!$_productCollection->count()): ?> 
		<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
	<?php else: ?>
	<?php
		// getConfig
		$widthImage  	= $this->getConfig('widthImage') ? $this->getConfig('widthImage') : 135;
		$heightImage 	= $this->getConfig('heightImage') ? $this->getConfig('heightImage') : 135;
		$price   		= $this->getConfig('price');
		$cart    		= $this->getConfig('cart');
		$compare  		= $this->getConfig('compare');
		$wishlist  		= $this->getConfig('wishlist');
		$review  		= $this->getConfig('review');
		$slide  		= $this->getConfig('slide');
		$rows 			= $this->getConfig('rows');
		$class 			= ($slide && $rows > 1) ? '.slide-multirows' : '.products-grid';
	?>
	<?php if ($slide && $rows > 1): ?>
		<div class="slide-multirows">
	<?php endif ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $j=0; $time = $this->getConfig('playDelay'); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php $t = $j*$time; $t .='ms'; $j++; ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item <?php if(($i-1)%$_columnCount==0): ?> first <?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> item-animate">
		<div class="item-inner">
					<div class="box-images">
					    <div class="imageslider">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($widthImage, $heightImage); ?>" width="<?php echo $widthImage?>" height="<?php echo $heightImage?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
						
					    </div>
						
						
					</div>
					<?php echo $helpLabels->getLabels($_product); //Product labels ?>
				
				    
				    
					<ul class="add-to-links">
					<?php if($cart): ?>
							<?php if($_product->isSaleable()): ?>
								<li class="button1"><button type="button" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')" title="Add to Cart"><span><span><i class="fa fa-shopping-cart"></i><?php //echo $this->__('Add to Cart') ?></span></span></button></li>
							<?php else: ?>
								<li><span class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></span></li>
							<?php endif; ?>
						<?php endif; ?>
					<?php if($compare || $wishlist): ?>
						<?php if($wishlist): ?>
							<?php if ($this->helper('wishlist')->isAllow()) : ?>
								<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><i class="fa fa-heart"></i></a></li>
							<?php endif; ?>
						<?php endif; ?>
						<?php if($compare): ?>
							<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								<li class="last"><a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" class="link-compare"><i class="fa fa fa-refresh"></i></a></li>
							<?php endif; ?>
						<?php endif; ?>
						    
						<?php endif; ?>
					</ul>
				    
				
				
				
				
				<div class="product-shop1">
				    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
				    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
				    
				    <?php if($review): ?>
					    <?php echo $this->getReviewsSummaryHtml($_product) ?>
				    <?php endif; ?>
				    <?php echo $this->getPriceHtml($_product, true) ?>
				
				</div>
				
		</div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
		<?php if ($slide && $rows > 1): ?>
		</div>
		<?php endif ?>
	<?php endif ?>
	
</div>

<?php if($slide) : ?>
<script type="text/javascript">
	jQuery(document).ready(function($){
		(function(selector){
			var $content = $(selector);
			var $slider  = $('<?php echo $class ?>', $content);
			var slider 	 = $slider.bxSlider({
				<?php echo $this->setBxslider() ?>
				//infiniteLoop: false,
				moveSlides:1,
				slideMargin: 2,
				autoHover: true, // stop while hover <=> slider.stopAuto(); + slider.startAuto();
			})

	       

		})(".featuredproduct");
	});
</script>
<?php endif ?>
