
<nav class="navbar navbar-inverse mega-menu-wapper">
    <div class="navbar-header">
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>

    <?php $_helper = Mage::helper('catalog/category') ?>
    <?php $_categories = $_helper->getStoreCategories() ?>
    <?php $currentCategory = Mage::registry('current_category') ?>
    <?php if (count($_categories) > 0): ?>
        <div class="collapse navbar-collapse js-navbar-collapse">
            <ul class="nav navbar-nav level1">
                <?php foreach($_categories as $_category): ?>
                    <li class="dropdown mega-dropdown">
                        <a href="<?php echo $_helper->getCategoryUrl($_category) ?>" class="dropdown-toggle" data-toggle="dropdown">
                            <?php $ID = $_category->getId(); ?>
                            <?php $thumb = Mage::getModel('catalog/category')->load($ID)->getImage(); ?>
                            <span class="furniture-icon" style="background:none">
                                        <img src="<?php echo Mage::getBaseUrl('media') . 'catalog/category/' . $thumb; ?>">
                                    </span>
                            <?php echo $_category->getName() ?>
                        </a>
                        <ul class="dropdown-menu mega-dropdown-menu">
                            <?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>
                            <?php $_subcategories = $_category->getChildrenCategories() ?>
                            <?php if (count($_subcategories) > 0): ?>
                                <li>
                                    <ul class="level2">
                                        <?php $i = 0; ?>
                                        <?php foreach($_subcategories as $_subcategory): ?>
                                            <?php if ($i++ == 4) break; ?>
                                            <li class="col-sm-3">
                                                <a href="<?php echo $_helper->getCategoryUrl($_subcategory) ?>">
                                                    <?php echo $_subcategory->getName() ?>
                                                </a>

                                                <?php $_subcategory2 = Mage::getModel('catalog/category')->load($_subcategory->getId()) ?>
                                                <?php $_subcategories2 = $_subcategory2->getChildrenCategories() ?>
                                                <?php if (count($_subcategories2) > 0): ?>
                                                    <ul class="level3">
                                                        <?php foreach($_subcategories2 as $_subcategory2): ?>
                                                            <li>
                                                                <a id="<?php echo $_subcategory2->getId()  ?>" href="<?php echo $_helper->getCategoryUrl($_subcategory2) ?>">
                                                                    <?php echo $_subcategory2->getName() ?>
                                                                </a>
                                                            </li>
                                                        <?php endforeach; ?>
                                                    </ul>
                                                <?php endif; ?>
                                            </li>
                                        <?php endforeach; ?>
                                        <li class="view-all">
                                            <a href="<?php echo $_helper->getCategoryUrl($_category) ?>">
                                                <?php echo $this->__('View All'); ?> <?php echo $_category->getName() ?>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            <?php endif; ?>
                        </ul>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>
</nav>