<?php
$title = $this->getData('title');
$identify = $this->generateRandomString();
$tabs = $this->getTabs();
?>
<div class="cat_banner">
	
		
<div class="cattab_container">
<div id="<?php echo $identify ?>">
	<div class="bx-title"><div class="bg-title"><h2><span class="text1">Cattabs</span><span class="text2">sale off</span></h2>
	<ul class="cattabs" data-options=<?php echo $this->getOptions() ?>>
		<?php
			$active = ' active';
			foreach ($tabs as $id => $name) {
				echo '<li data-catid ="'.$id.'" class="item'.$active.'">'.$name.'</li>';
				$active = '';
			}
		?>
	</ul></div></div>
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_image1')->toHtml() ?>
	<div class="ajax_loading" style="display:none">
			<i class="fa fa-spinner fa-spin"></i>
		</div>
	<div class="cattabs-products"></div>
</div>
</div>
	
	
	
</div>
<script type="text/javascript">
	jQuery( document ).ready(function($) {
		(function(selector){
			var $content = $(selector);
			var cattabs  = $('.cattabs', $content);
			var options  = cattabs.data('options');
			var $items 	 = $('.item', cattabs);
			var $loading = $(".ajax_loading", $content);
			var $products= $('.cattabs-products', $content);
			var info 	 = {catId:$items.first().data('catid')};
			$.extend(info, options);
			
			$items.click(function() {
				info = {catId:$(this).data('catid')};
				$.extend(info, options);
				if($(this).hasClass('active')) return;
				$items.removeClass('active');
				$(this).addClass('active');
				getProduct(info);
				
			});
			getProduct(info);
			function getProduct(data) {
				$loading.show();
				$.ajax({
					type:'post',
					data: data,
					url:'<?php echo $this->getUrl('cattabs/index/ajax')?>',
					success: function(data){
						$loading.hide();
						$products.html(data);		
						$data = data;
						$('.products-grid', $products).bxSlider({
							infiniteLoop: false,
							<?php echo $this->setBxslider()?>
						});
						ajaxTooltipAfter()
					},
				});		
			}
		})("#<?php echo $identify ?>");
	});
</script>

