    
<div class="owl-carousel owl-theme">
    <div class="item"><img src="http://www.storieshomes.com/media/youama/slider/default/studytable_bannerq.jpg" class="img-responsive" /></div>
    <div class="item"><img src="http://www.storieshomes.com/media/youama/slider/default/studytable_bannerq.jpg" class="img-responsive" /></div>
</div>

<div class="shop-by-cat">
  <h3 class="title">SHOP BY CATEGORY</h3>
  <ul class="list-inline category-links">
    <li>
      <a href="#">
      <i class="flaticon flaticon-furniture"></i>
      <h5>Furniture</h5>
      </a>
    </li>
    <li>
      <a href="#">
      <i class="flaticon flaticon-theatrical-scene"></i>
      <h5>Furnishing</h5>
      </a>
    </li>
    <li>
      <a href="#">
      <i class="flaticon flaticon-light"></i>
      <h5>Lights</h5>
      </a>
    </li>
    <li>
      <a href="#">
      <i class="flaticon flaticon-rug"></i>
      <h5>Carpets</h5>
      </a>
    </li>
    <li>
      <a href="#">
      <i class="flaticon flaticon-vases"></i>
      <h5>Accessories</h5>
      </a>
    </li>
    <li>
      <a href="#">
      <i class="flaticon flaticon-picture-frames"></i>
      <h5>Frames</h5>
      </a>
    </li>
    <li>
      <a href="#">
      <i class="flaticon flaticon-stove" aria-hidden="true"></i>
      <h5>Kitchen</h5>
      </a>
    </li>
    <li>
      <a href="#">
      <i class="flaticon flaticon-vacuum-cleaner" aria-hidden="true"></i>
      <h5>Housekeeping</h5>
      </a>
    </li>
  </ul>
  <div class="shop-by-footer"><a href="#">VIEW ALL</a></div>
</div> <!-- // Shop by category -->



<div class="homepage-product feature-products">
  <h3 class="title">FEATURED PRODUCTS</h3>
  <ul class="list-inline">
    <li>
      <div class="img-holder">
      <a href=""><img src="http://www.storieshomes.com/media/catalog/product/cache/1/small_image/236x260/9df78eab33525d08d6e5fb8d27136e95/5/4/5487_16_.jpg" class="img-responsive" />
      </a>
      </div>
      <a href="" class="product-title">Bejeu sofa 3 seater</a>
      <span class="product-category">3 Seater</span>
      <h5 class="product-price">AED 179.00</h5>
      <a href="" class="add-cart-btn">shop now</a>
    </li>

    <li>
      <div class="img-holder">
      <a href=""><img src="http://www.storieshomes.com/media/catalog/product/cache/1/small_image/236x260/9df78eab33525d08d6e5fb8d27136e95/2/1/2166.jpg" class="img-responsive" />
      </a>
      </div>
      <a href="" class="product-title">Chital Purple Jug</a>
      <span class="product-category">Jug</span>
      <h5 class="product-price">AED 179.00</h5>
      <a href="" class="add-cart-btn">shop now</a>
      
    </li>

    <li>
      <div class="img-holder">
      <a href=""><img src="http://www.storieshomes.com/media/catalog/product/cache/1/small_image/236x260/9df78eab33525d08d6e5fb8d27136e95/1/_/1_4_.jpg" class="img-responsive" />
      </a>
      </div>
      <a href="" class="product-title">GALAXY SHOWPIECE RED</a>
      <span class="product-category">SHOWPIECE</span>
      <h5 class="product-price">AED 179.00</h5>
      <a href="" class="add-cart-btn">shop now</a>
      
    </li>

    <li>
      <div class="img-holder">
      <a href=""><img src="http://www.storieshomes.com/media/catalog/product/cache/1/small_image/236x260/9df78eab33525d08d6e5fb8d27136e95/i/m/img_0005_4_a_1.jpg" class="img-responsive" />
      </a>
      </div>
      <a href="" class="product-title">Lenovo A1000 Dual Sim Smartphone, 3G - 8GB </a>
      <span class="product-category">Jug</span>
      <h5 class="product-price">AED 179.00</h5>
      <a href="" class="add-cart-btn">shop now</a>
      
    </li>
  </ul>
</div>



<div class="homepage-product top-category-products"> <!-- Popular product -->
  <h3 class="title">TOP CATEGORY</h3>
  <ul class="list-inline">
    <li>
      <div class="img-holder">
      <a href=""><img src="http://www.storieshomes.com/media/catalog/product/cache/1/small_image/236x260/9df78eab33525d08d6e5fb8d27136e95/1/_/1_166_.jpg" class="img-responsive" />
      </a>
      </div>
      <a href="" class="product-title">CERAMIC FRUIT TRAY</a>
      <span class="product-category">FRUIT TRAY</span>
      <h5 class="product-price">AED 179.00</h5>
      <a href="" class="add-cart-btn">shop now</a>
      
    </li>

    <li>
      <div class="img-holder">
      <a href=""><img src="http://www.storieshomes.com/media/catalog/product/cache/1/small_image/236x260/9df78eab33525d08d6e5fb8d27136e95/1/_/1_21_.jpg" class="img-responsive" />
      </a>
      </div>
      <a href="" class="product-title">LOVE SHAPED VASE</a>
      <span class="product-category">VASE</span>
      <h5 class="product-price">AED 179.00</h5>
      <a href="" class="add-cart-btn">shop now</a>
      
    </li>

    <li>
      <div class="img-holder">
      <a href=""><img src="http://www.storieshomes.com/media/catalog/product/cache/1/small_image/236x260/9df78eab33525d08d6e5fb8d27136e95/i/m/img_0031.jpg" class="img-responsive" />
      </a>
      </div>
      <a href="" class="product-title">VALENCIA COT</a>
      <span class="product-category">COT</span>
      <h5 class="product-price">AED 179.00</h5>
      <a href="" class="add-cart-btn">shop now</a>
      
    </li>

    <li>
      <div class="img-holder">
      <a href=""><img src="http://www.storieshomes.com/media/catalog/product/cache/1/small_image/236x260/9df78eab33525d08d6e5fb8d27136e95/i/m/img_0005_4_a_1.jpg" class="img-responsive" />
      </a>
      </div>
      <a href="" class="product-title">SOFA 2 SEATER</a>
      <span class="product-category">2 SEATER</span>
      <h5 class="product-price">AED 179.00</h5>
      <a href="" class="add-cart-btn">shop now</a>
      
    </li>
  </ul>
</div> <!-- // Popular product -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript">
        jQuery(".owl-carousel").owlCarousel({
            nav: true,
            loop: false,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 1
                },
                1000: {
                    items: 1
                }
                1200: {
                    items: 1
                }
            }
        });
    </script>