<!doctype html>
<title>Magento Maintenance mode</title>
<style>
  body { text-align: center; padding: 150px; }
  h1 { font-size: 50px; }
  body { font: 20px Helvetica, sans-serif; color: #333; }
  article { display: block; text-align: center; width: 650px; margin: 0 auto; }
  a { color: #dc8100; text-decoration: none; }
  a:hover { color: #333; text-decoration: none; }
</style>
 
<article>
    <h1>We'll be back soon!</h1>
    <div>
        <p>Sorry for the inconvenience. storieshomes.com is performing maintenance at the moment. If you need any help please <a href="mailto:info@storieshomes.com">contact us.</a></p>
        
        <img src="http://www.storieshomes.com/skin/frontend/rwd/default/images/logo.jpg" class="logo-image" alt="Magento tutorial">
        
 
    </div>
</article>