<?php
if(!Mage::getStoreConfig('relatedslider/general/enabled')) return;
?>
<?php if(!$this->getItems()->getSize()) return; ?>
<?php
    $_helper = Mage::helper('relatedslider');
    // getConfig
    $widthImage     = $_helper->getConfig('widthImage') ? $_helper->getConfig('widthImage') : 135;
    $heightImage    = $_helper->getConfig('heightImage') ? $_helper->getConfig('heightImage') : 135;
    $price          = $_helper->getConfig('price');
    $cart           = $_helper->getConfig('cart');
    // $compare        = $this->getConfig('compare');
    $wishlist       = $_helper->getConfig('wishlist');
    $review         = $_helper->getConfig('review');
    // $rows           = $this->getConfig('rows');
    // $class          = ($rows > 1) ? '.slide-multirows' : '.products-grid';
?>

<div class="relatedslider">
    <?php echo $_helper->getConfig('title') ? '<div class="bx-title related-title"><div class="bg-title"><h2 class="title">' .$_helper->getConfig('title'). '</h2></div></div>' : ''; ?>
    
    <ul class="products-grid" id="block-related">
    <?php foreach($this->getItems() as $_item): ?>
        <li class="item">
            <div class="related-subtitle">
        <?php echo $this->__('Check items to add to the cart') ?>
        <?php if(!$_item->isComposite() && $_item->isSaleable()): ?>
                <?php if (!$_item->getRequiredOptions()): ?>
        <input type="checkbox" class="checkbox related-checkbox" id="related-checkbox<?php echo $_item->getId() ?>" name="related_products[]" value="<?php echo $_item->getId() ?>" />
        <?php endif; ?>
            <?php endif; ?>
        <?php echo $this->__(' or ') ?>
        <a href="#" onclick="selectAllRelated(this); return false;"><?php echo $this->__('select all') ?></a>
    </div>
            <div class="item-inner">
                <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize( $widthImage, $heightImage ) ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
                <div class="product-details">
                    <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></p> 
					<?php if( $price ): ?>
                        <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                    <?php endif; ?>
                    <?php if( $review ): ?>
                        <?php echo $this->getReviewsSummaryHtml($_item) ?>
                    <?php endif; ?>
                    
                </div>
            </div>
        </li>
    <?php endforeach ?>
    </ul>
</div>
<script type="text/javascript">decorateList('block-related', 'none-recursive')</script>
<script type="text/javascript">
    //<![CDATA[
    $$('.related-checkbox').each(function(elem){
        Event.observe(elem, 'click', addRelatedToProduct)
    });

    var relatedProductsCheckFlag = false;
    function selectAllRelated(txt){
        if (relatedProductsCheckFlag == false) {
            $$('.related-checkbox').each(function(elem){
                elem.checked = true;
            });
            relatedProductsCheckFlag = true;
            txt.innerHTML="<?php echo $this->__('unselect all') ?>";
        } else {
            $$('.related-checkbox').each(function(elem){
                elem.checked = false;
            });
            relatedProductsCheckFlag = false;
            txt.innerHTML="<?php echo $this->__('select all') ?>";
        }
        addRelatedToProduct();
    }

    function addRelatedToProduct(){
        var checkboxes = $$('.related-checkbox');
        var values = [];
        for(var i=0;i<checkboxes.length;i++){
            if(checkboxes[i].checked) values.push(checkboxes[i].value);
        }
        if($('related-products-field')){
            $('related-products-field').value = values.join(',');
        }
    }

    jQuery(document).ready(function($){
        (function(selector){
            var $content = $(selector);
            var $slider  = $('.products-grid', $content);
            var slider   = $slider.bxSlider({
                <?php echo $_helper->setBxslider() ?>
                //infiniteLoop: false,
                moveSlides:1,
                slideMargin: 0,
                autoHover: true, // stop while hover <=> slider.stopAuto(); + slider.startAuto();
            })

        })(".relatedslider");
    });

    //]]>
</script>
