<?php
/**
 *
 * @category   Rohde
 * @package    Rohde_Onestepcheckout
 * @author     Support <j.rohde@nederland.live>
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Edit Account Information') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" autocomplete="off">
    <div class="fieldset">
        <?php
        $attribute = Mage::getModel('eav/config')->getAttribute('customer', 'account_type');
        $_account_typeLabel = $attribute->getSource()->getOptionText($this->getCustomer()->getAccountType());
        ?>
        <?php echo $this->getBlockHtml('formkey') ?>
        <h2 class="legend"><?php echo $this->__('Account Information') ?></h2>
        <ul class="form-list">
            <?php $_account_type = $this->getLayout()->createBlock('onestepcheckout/widget_accounttype') ?>
            <?php if ($_account_type->isEnabled()): ?>
                <li class="wide hide">
                    <?php echo $_account_type->setAccountType($this->getCustomer()->getAccountType())->setFieldParams('disabled')->toHtml() ?>
                </li>
            <?php endif ?>
            <li class="fields">
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
            </li>
            <li>
                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" name="email" id="email" readonly="" value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email" />
                </div>
            </li>
            <li class="control">
                <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if ($this->getCustomer()->getChangePassword() == 1): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="change_password"><?php echo $this->__('Change Password') ?></label>
            </li>
        </ul>
    </div>
    <div class="fieldset" style="display:none;">
        <h2 class="legend"><?php echo $this->__('Change Password') ?></h2>
        <ul class="form-list">
            <li>
                <label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>
                <div class="input-box">
                    <input type="text" class="input-text no-display" name="dummy" id="dummy" />
                    <input type="password" title="<?php echo $this->__('Current Password') ?>" class="input-text" name="current_password" id="current_password" />
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo $this->__('New Password') ?>" class="input-text validate-password" name="password" id="password" />
                    </div>
                </div>
                <div class="field">
                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
                    <div class="input-box">
                        <input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <?php $_dob = $this->getLayout()->createBlock('onestepcheckout/widget_dob') ?>
    <?php $_gender = $this->getLayout()->createBlock('onestepcheckout/widget_gender') ?>
    <?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Additional Information') ?></h2>
        <ul class="form-list">
            <li>
                <ul id="account_type-area"  style="overflow: hidden;display:block;">
                    <li class="fields">
                        <?php if ($_dob->isEnabled()): ?>
                        <div class="field">
                            <?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?>
                        </div>
                        <?php endif ?>
                        <?php if ($_gender->isEnabled()): ?>
                        <div class="field">
                            <?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?>
                        </div>
                        <?php endif ?>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <?php endif ?>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    dataForm.submit = function(button, url) {
        if (this.validator.validate()) {
            if (button && button != 'undefined') {
                button.disabled = true;
            }
        }
    }.bind(dataForm);
    function setPasswordForm(arg) {
        if (arg) {
            $('current_password').up(3).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        } else {
            $('current_password').up(3).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }

<?php if ($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
<?php endif; ?>
//]]>
</script>
