<?php if($this->canShowBlock()): ?>
    <div class="block block-layered-nav ajaxlayerednav-content">
        <div class="block-title">
            <strong><span><?php echo Mage::helper('ajaxlayerednavigation')->__('Shop By') ?></span></strong>
        </div>
        <div class="block-content">
            <?php echo $this->getStateHtml() ?>

            <?php if($this->canShowOptions()): ?>
                <dl id="narrow-by-list">
                    <?php $_filters = $this->getFilters() ?>
                    <?php foreach ($_filters as $_filter): ?>
                        <?php if($_filter->getItemsCount()): ?>
                            <dt>
                                <?php if (Mage::getStoreConfig('ajaxlayerednavigation/general/style') == '3') : ?>
                                <span class="ajaxlayered-expander">
                                    <?php echo $this->__($_filter->getName()) ?>
                                </span>
                                <?php else : ?>
                                    <?php echo $this->__($_filter->getName()) ?>
                                <?php endif; ?>
                            </dt>
                            <dd><?php echo $_filter->getHtml() ?></dd>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </dl>
                <script type="text/javascript">decorateDataList('narrow-by-list')</script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>