<?php if($this->canShowBlock()): ?>
<div class="block block-layered-nav">
    <div class="block-title">
        <strong><span><?php echo Mage::helper('ajaxlayerednavigation')->__('Shop By') ?></span></strong>
    </div>
    <div class="block-content">
        <?php echo $this->getStateHtml() ?>

        <?php if($this->canShowOptions()): ?>
            <p class="block-subtitle"><?php echo Mage::helper('ajaxlayerednavigation')->__('Shopping Options') ?></p>
            <dl id="narrow-by-list">
                <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                    <?php if($_filter->getItemsCount() > 0): ?>
                        <dt><?php echo $this->__($_filter->getName()) ?></dt>
                        <dd><?php echo $_filter->getHtml() ?></dd>
                    <?php endif; ?>
                <?php endforeach; ?>
            </dl>
            <script type="text/javascript">decorateDataList('narrow-by-list')</script>
        <?php endif; ?>
    </div>
</div>

<?php endif; ?>