<div class="input-box">
    <input name="filter-by-name" id="filter-by-name" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Name')) ?>" value="<?php echo $this->escapeHtml($this->getFilter()->getActiveValue()) ?>" class="input-text" type="text" />
    <button type="button" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Apply')) ?>" class="button aln-apply-name"><span><span><?php echo Mage::helper('contacts')->__('Apply') ?></span></span></button>
</div>